// AUTO-GENERATED by open_notebook_creator_sdk.codegen — DO NOT EDIT.
// Source of truth: open-notebook-creator-sdk SCHEMA_REGISTRY.
import { z } from "zod";

// === flashcards.v1 ===
export const FlashcardsV1Schema = z.object({
  deck_name: z.string(),
  cards: z.array(z.object({
  id: z.string(),
  front: z.string(),
  back: z.string(),
  tags: z.array(z.string()).optional(),
})),
});
export type FlashcardsV1 = {
  deck_name: string;
  cards: Array<{
  id: string;
  front: string;
  back: string;
  tags?: Array<string>;
}>;
};

// === chart_spec.v1 ===
export const ChartSpecV1Schema = z.object({
  library: z.string().optional(),
  title: z.string().nullable().optional(),
  specs: z.array(z.record(z.string(), z.unknown())).optional(),
});
export type ChartSpecV1 = {
  library?: string;
  title?: (string | null);
  specs?: Array<Record<string, unknown>>;
};

// === infographic.v1 ===
export const InfographicV1Schema = z.object({
  title: z.string(),
  subtitle: z.string().nullable().optional(),
  blocks: z.array(z.object({
  type: z.string(),
  value: z.string().nullable().optional(),
  label: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  icon: z.string().nullable().optional(),
  heading: z.string().nullable().optional(),
  body: z.string().nullable().optional(),
  items: z.array(z.string()).nullable().optional(),
  text: z.string().nullable().optional(),
  attribution: z.string().nullable().optional(),
})).optional(),
});
export type InfographicV1 = {
  title: string;
  subtitle?: (string | null);
  blocks?: Array<{
  type: string;
  value?: (string | null);
  label?: (string | null);
  description?: (string | null);
  icon?: (string | null);
  heading?: (string | null);
  body?: (string | null);
  items?: (Array<string> | null);
  text?: (string | null);
  attribution?: (string | null);
}>;
};

// === infographic.v2 ===
export const InfographicV2Schema = z.object({
  library: z.string().optional(),
  title: z.string().nullable().optional(),
  spec: z.string().optional(),
  theme: z.string().nullable().optional(),
});
export type InfographicV2 = {
  library?: string;
  title?: (string | null);
  spec?: string;
  theme?: (string | null);
};

// === mindmap.v1 ===
export const MindmapV1Schema = z.object({
  title: z.string(),
  mermaid_syntax: z.string(),
  description: z.string().nullable().optional(),
});
export type MindmapV1 = {
  title: string;
  mermaid_syntax: string;
  description?: (string | null);
};

// === audio.v1 ===
export const AudioV1Schema = z.object({
  transcript: z.array(z.record(z.string(), z.unknown())).nullable().optional(),
  outline: z.record(z.string(), z.unknown()).nullable().optional(),
  duration_seconds: z.number().nullable().optional(),
});
export type AudioV1 = {
  transcript?: (Array<Record<string, unknown>> | null);
  outline?: (Record<string, unknown> | null);
  duration_seconds?: (number | null);
};

// === textbook.v1 ===
export const TextbookV1Schema = z.object({
  title: z.string(),
  subtitle: z.string().nullable().optional(),
  chapters: z.array(z.object({
  title: z.string(),
  summary: z.string().nullable().optional(),
})).optional(),
  formats: z.array(z.string()).optional(),
});
export type TextbookV1 = {
  title: string;
  subtitle?: (string | null);
  chapters?: Array<{
  title: string;
  summary?: (string | null);
}>;
  formats?: Array<string>;
};

export const SCHEMA_VALIDATORS: Record<string, z.ZodTypeAny> = {
  "flashcards.v1": FlashcardsV1Schema,
  "chart_spec.v1": ChartSpecV1Schema,
  "infographic.v1": InfographicV1Schema,
  "infographic.v2": InfographicV2Schema,
  "mindmap.v1": MindmapV1Schema,
  "audio.v1": AudioV1Schema,
  "textbook.v1": TextbookV1Schema,
};
