// AUTO-GENERATED by open_notebook_creator_sdk.codegen — DO NOT EDIT.
// Source of truth: open-notebook-creator-sdk SCHEMA_REGISTRY.
import { z } from "zod";

// === flashcards.v1 ===
export const FlashcardsV1Schema = z.object({
  deck_name: z.string(),
  cards: z.array(z.object({
  id: z.string(),
  front: z.string(),
  back: z.string(),
  tags: z.array(z.string()).optional(),
})),
});
export type FlashcardsV1 = {
  deck_name: string;
  cards: Array<{
  id: string;
  front: string;
  back: string;
  tags?: Array<string>;
}>;
};

// === chart_spec.v1 ===
export const ChartSpecV1Schema = z.object({
  library: z.string().optional(),
  title: z.string().nullable().optional(),
  specs: z.array(z.record(z.string(), z.unknown())).optional(),
});
export type ChartSpecV1 = {
  library?: string;
  title?: (string | null);
  specs?: Array<Record<string, unknown>>;
};

// === audio.v1 ===
export const AudioV1Schema = z.object({
  transcript: z.array(z.record(z.string(), z.unknown())).nullable().optional(),
  outline: z.record(z.string(), z.unknown()).nullable().optional(),
  duration_seconds: z.number().nullable().optional(),
});
export type AudioV1 = {
  transcript?: (Array<Record<string, unknown>> | null);
  outline?: (Record<string, unknown> | null);
  duration_seconds?: (number | null);
};

export const SCHEMA_VALIDATORS: Record<string, z.ZodTypeAny> = {
  "flashcards.v1": FlashcardsV1Schema,
  "chart_spec.v1": ChartSpecV1Schema,
  "audio.v1": AudioV1Schema,
};
